
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /home/pi/homeassistant/:/config/
    ports:
      - "8123:8123"  
    environment:
      - TZ=Europe/Kiev
    restart: always
    privileged: true
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - /home/pi/mosquitto/:/mosquitto/config/
      - /home/pi/mosquitto/data/:/mosquitto/data/
      - /home/pi/mosquitto/log/:/mosquitto/log/
    ports:
      - "9001:9001"  
    environment:
      - TZ=Europe/Kiev
    restart: always
    privileged: true
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - /home/pi/z2m/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Kiev
  torrserver:
    container_name: torrserver
    image: sergge1/torrserver:latest
    volumes:
      - /home/pi/torrserver/db/:/torrserver/db/
    ports:
      - "8090:8090"  
    environment:
      - TZ=Europe/Kiev
    restart: always
    privileged: true  